# Adds namespace to all resources.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ecosia-master

resources:
- web/config-map.yaml
- web/deployment.yaml
- web/service.yaml
- ingress.yaml
- web/namespace.yaml
images:
- name: 265311748595.dkr.ecr.us-east-2.amazonaws.com/ecosia
  newTag: 993a9cc7
