name: Deploy to Kubernetes cluster

on:
  push:
    branches: [ master ]
env:
  CLUSTER: ${{ secrets.CLUSTER }}
  
jobs:
  deploy:
    name: Deploy to Kubernetes
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

      # login with AWS config details
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    # login to ECR to be able to pull image
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    # update the kubeconfig file and set as current context 
    - name: Update kube config
      run: aws eks update-kubeconfig --name $CLUSTER --region us-east-2
       
   # Download and apply all files using kustomize
    - name: Deploy to K8s
      run: |
       curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"  | bash
       ./kustomize build master | kubectl apply -f -
